################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/board/ra4e2_fpb \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra4e2 \
ra/fsp/src/r_dtc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_ioport \
ra/fsp/src/r_sci_spi \
ra/fsp/src/r_sci_uart \
ra_gen \
src/SEGGER_RTT \
src/SRC/API/NATIVE_TAG/T2T \
src/SRC/API/NATIVE_TAG/T3T \
src/SRC/API/NATIVE_TAG/T4T \
src/SRC/API/NATIVE_TAG/T5T \
src/SRC/API/NDEF/GENERIC \
src/SRC/API/NDEF/TAG_TYPES/NDEF_T2T \
src/SRC/API/NDEF/TAG_TYPES/NDEF_T3T \
src/SRC/API/NDEF/TAG_TYPES/NDEF_T4T \
src/SRC/API/NDEF/TAG_TYPES/NDEF_T5T \
src/SRC/API/RUL \
src/SRC/COMPS/HAL/DRV/MCU/RA4M2 \
src/SRC/COMPS/HAL \
src/SRC/COMPS/HIP/RUL \
src/SRC/COMPS/HIP \
src/SRC/COMPS/LOG/NONE \
src/SRC/COMPS/LOG \
src/SRC/COMPS/NSC/RUL \
src/SRC/COMPS/NSC/UCODE \
src/SRC/COMPS/NSC \
src/SRC/COMPS/UTILS \
src/SRC/EXAMPLES/Utils \
src/SRC/EXAMPLES/ptx_Example_NFCForumNDEF \
src \

